---
name: Test yamllint and kubeconform
on:
  push:
    branches:
      - main
    paths:
      - '**.yaml'
      - '**.yml'
  pull_request:
    paths:
      - '**.yaml'
      - '**.yml'
  workflow_dispatch: # Allows manual triggering

jobs:
  lint-and-validate:
    # Points to central ci-template repo
    uses: hitesha1981/ci-templates/.github/workflows/kubeconform.yaml@main
    with:
      kube_version: "1.31.0"
      strict: true